### ISSUE TITLE
linux OS not supported

### ISSUE THREAD

**Issue by enigma119** [Tenpi/crunchyroll.ts#2]
Hello!
I was trying to install this module but unfortunately it cannot be installed on linux yet.
My current operating system is Ubuntu 20
I can say you did a great job just reading the doc

**Comment by Tenpi** [comment]
Hi, one of the dependencies [ntsuspend](https://github.com/FedericoCarboni/node-ntsuspend) seems to be Windows exclusive. Unfortunately there isn't much that I can do about that, but you can fork this repo, remove that package, and use your fork. I believe that you won't be able to pause/resume the video downloads.
