### ISSUE TITLE
Feature Request: Unsupported platform for ntsuspend@1.0.1

### ISSUE THREAD

**Issue by dmgolembiowski** [Tenpi/crunchyroll.ts#3]
### Description
> `ntsuspend` dependency breaks linux/unix clients

```sh
npm install crunchyroll.ts
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for ntsuspend@1.0.1: wanted {"os":"win32","arch":"x64,ia32"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  x64,ia32
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```
### Proposed Resolution
> Prepare a separate dependencies list, [unique `add` & `build` files](https://docgov.dev/posts/npm-scripts/#create-node-script), and separated `npm build`/`npm install` scripts that are noted [under "scripts" in `./package.json`](https://github.com/Tenpi/crunchyroll.ts/blob/master/package.json#L7-L10); or maybe split the repository into two distinct ones: WinOS / Unix

**Comment by Tenpi** [comment]
I made this dependency optional in `v0.3.2`. I hope that fixes your issues.
