### ISSUE TITLE
esLA (Latinoamerican spanish) is not the same esES (Spanish from Spain)

### ISSUE THREAD

**Issue by sl1pkn07** [Tenpi/crunchyroll.ts#5]
Hi

i use your Crunchyroll Downloader (wich use this npm module) for download frm CR in Spanish (spain) subtitles/audio. but when select Spanish language always download the Latinoamerican Spanish version

in the code i see you treat both language as the same language

https://github.com/Tenpi/crunchyroll.ts/blob/17f80de53085aa990fecbadfa09d380df49b9c2a/entities/Util.ts#L77-L78

in CR, Spanish latinoamerican seems set first in the priority list, so is selected by default

is possible separate esLA and esES as independent language?

i can understand both perfectly, only change some words and expressions, but as Spanish native from spain, the spanish (esES) is more natural than latinoamerican for me. 

greetings

**Comment by Tenpi** [comment]
I don't think that it's worth separating the different dialects eg. English (US) vs English (UK), Spanish (ES) vs Spanish (LA), etc. because the differences are so small. That's why I only picked one (the dialect that I think more people speak).

I could however change the default for Spanish to be esES if there are more people who speak that dialect.

**Comment by sl1pkn07** [comment]
> I could however change the default for Spanish to be esES if there are more people who speak that dialect.

then the latinamerica users refuse the changes

i think is better separate, or add an option in advance for set the specified dialect, or pick up from the system locale (i'm linux user, so 

~~~
└───╼  locale
LANG=es_ES.UTF-8
---cut---
~~~

or something similar

greetings

**Comment by Tenpi** [comment]
Will see if I add an option in advanced settings that seems to be the best solution here.

**Comment by Tenpi** [comment]
Added in `v0.3.9`
