### ISSUE TITLE
Connection problem with the session

### ISSUE THREAD

**Issue by Ziedelth** [Tenpi/crunchyroll.ts#7]
Hi,
I tried the project and found that there was a problem with the sessions, plus other issues had the same problem.

I searched a bit and a difficulty occurred on the "access_token" and the "device_type".
I found the solution on another repository that has the same problem (https://github.com/streamlink/streamlink/issues/4453)

The new token is "LNDJgOit5yaRIWN" and the device_type is "com.crunchyroll.windows.desktop".
I tested the solution with Postman and the request went through without problems.

![image](https://user-images.githubusercontent.com/45169338/192230398-1b016c3b-9d8d-4861-90f8-da97bb366d7f.png)

**Comment by Tenpi** [comment]
Thank you very much for providing the new token and device_type, updated.
